$(document).ready(function(){
	$('#ntc').click(function(){
		location.href="centerBoardNotice.do";
	})
	$('#song').click(function(){
		location.href="centerBoardSong.do";
	})
	$('#cent').click(function(){
		location.href="centerBoardMain.do";
	})
	$('#train').click(function(){
		location.href="centerBoardTrainer.do";
	})
	$('.dbtn').click(function(){
		$(this).siblings('.imgfrm').children('.file').click();
	})
	$('.file').change(function(){
		$(this).parent('.imgfrm').submit();
	})
});