$(document).ready(function(){
	$('.ebody').hide();
	$('.esbtn').hide();
	$('.d3').slideUp(1);
	$('.d2').click(function(){
		$(".d4").fadeOut(1);
		$(".d3").slideDown(450);
	});
	$('.cbtn').click(function(){
		$(".d3").fadeOut(1);
		$(".d4").fadeIn(1);
	});
	$('.rbox').hide();
	$('.rbtn').click(function(){
		$(this).parent('.notice').children('.lbtn').hide();
		$(this).parent('.notice').children('.rbtn').hide();
		$(this).parent('.notice').children('.rbox').show();
		$(this).parent('.notice').children('.rbox').slideUp(1);
		$(this).parent('.notice').children('.rbox').slideDown(400);
	});
	$('.rcbtn').click(function(){
		$(this).parent('.rbox').fadeOut(1);
		$(this).parent('.rbox').siblings('.lbtn').show();
		$(this).parent('.rbox').siblings('.rbtn').show();
	});
	$('#ntc').click(function(){
		$('.fnofrm').attr('action','centerBoardNotice.do');
		$('.fnofrm').submit();
	})
	$('#song').click(function(){
		$('.fnofrm').attr('action','centerBoardSong.do');
		$('.fnofrm').submit();
	})
	$('#cent').click(function(){
		$('.fnofrm').attr('action','centerBoardMain.do');
		$('.fnofrm').submit();
	})
	$('#train').click(function(){
		$('.fnofrm').attr('action','centerBoardTrainer.do');
		$('.fnofrm').submit();
	})
	$('.wbtn').click(function(){
		var str = $('.body').val();
		$('.frm').submit();
	});
	$('.ebtn').click(function(){
		$(this).parent('.notice').children('.nbody').fadeOut(1);
		$(this).parent('.notice').children('.lbtn').hide();
		$(this).parent('.notice').children('.rbtn').hide();
		$(this).parent('.notice').children('.ebtn').hide();
		$(this).parent('.notice').children('.esbtn').fadeIn(1);
		$(this).parent('.notice').children('.ebody').fadeIn(1);
		$(this).parent('.notice').children('.esbtn').css("margin-top","10px");
		$(this).parent('.notice').children('.dbtn').css("margin-top","10px");
	});
	$('.esbtn').click(function(){
		$(this).parent('.notice').children('.edtfrm').submit();
	});
	$('.dbtn').click(function(){
		$(this).children('.del').submit();
	})
});