$(document).ready(function(){
	$('#ntc').click(function(){
		$('.fnofrm').attr('action','centerBoardNotice.do');
		$('.fnofrm').submit();
	})
	$('#song').click(function(){
		$('.fnofrm').attr('action','centerBoardSong.do');
		$('.fnofrm').submit();
	})
	$('#cent').click(function(){
		$('.fnofrm').attr('action','centerBoardMain.do');
		$('.fnofrm').submit();
	})
	$('#train').click(function(){
		$('.fnofrm').attr('action','centerBoardTrainer.do');
		$('.fnofrm').submit();
	})
	$('.dbtn').click(function(){
		$(this).siblings('.imgfrm').children('.file').click();
	})
	$('.file').change(function(){
		$(this).parent('.imgfrm').submit();
	})
});